package me.ltthuc.kmp.core.content

import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The manifest is generated by `scripts/build_content_manifest.py`; this pins the shape the
 * app relies on, so a change on the script side fails here instead of at runtime on a
 * child's device.
 */
class ContentManifestTest {

    private val json = Json { ignoreUnknownKeys = true }

    private val sample = """
        {
          "version": 1,
          "hashLength": 10,
          "packs": {
            "L2U3": { "files": 2, "bytes": 300, "bundled": false },
            "L2U4": { "files": 3, "bytes": 400, "bundled": true },
            "core": { "files": 474, "bytes": 17342739, "bundled": true }
          },
          "assets": {
            "audio/level_2/unit_03/L2U03_SHORT-E_web/02_chant.mp3": {
              "hash": "2e28020587", "bytes": 100, "pack": "L2U3"
            },
            "images/level_2/stories/L2_S03/scene_1.webp": {
              "hash": "9f1c3d0a44", "bytes": 200, "pack": "L2U3"
            }
          }
        }
    """.trimIndent()

    private fun manifest() = json.decodeFromString<ContentManifest>(sample)

    @Test
    fun parsesGeneratedShape() {
        val manifest = manifest()
        assertEquals(1, manifest.version)
        assertEquals(10, manifest.hashLength)
        assertEquals(2, manifest.assets.size)
        assertEquals("2e28020587", manifest.assets.values.first().hash)
    }

    @Test
    fun bundledAssetsAreAbsentSoTheyResolveAsShippedInTheApp() {
        // The generator omits core assets on purpose — absence IS the "it ships in the app"
        // signal, and listing them would inflate the file 2.5x.
        assertNull(manifest().assets["audio/level_1/unit_01/L1U01_A_apple/00_sound_intro.mp3"])
    }

    @Test
    fun packListsBothAudioAndImages() {
        val pack = manifest().assetsInPack("L2U3")
        assertEquals(2, pack.size)
        assertTrue(pack.keys.any { it.endsWith(".mp3") })
        assertTrue(pack.keys.any { it.endsWith(".webp") })
    }

    @Test
    fun onlyPublishedPacksAreDownloadable() {
        // L2U4 is assigned to a pack but its bytes are not on the CDN yet, so it must
        // still be treated as shipped-in-app. Getting this backwards breaks those lessons.
        assertEquals(setOf("L2U3"), manifest().downloadablePackIds())
        assertTrue(manifest().isPackBundled("L2U4"))
        assertTrue(manifest().isPackBundled("core"))
    }

    @Test
    fun unknownPackCountsAsBundled() {
        assertTrue(manifest().isPackBundled("L9U9"))
    }

    @Test
    fun urlPutsTheHashInThePathSoChangedBytesMeanADifferentUrl() {
        val asset = ContentAsset(hash = "2e28020587", bytes = 100, pack = "L2U3")
        val path = "audio/level_2/unit_03/L2U03_SHORT-E_web/02_chant.mp3"

        assertEquals(
            "https://cdn.example.com/content/2e28020587/$path",
            contentUrl("https://cdn.example.com/content", path, asset),
        )
    }

    @Test
    fun urlToleratesATrailingSlashInTheBase() {
        val asset = ContentAsset(hash = "abc0000000", bytes = 1, pack = "L2U3")
        assertEquals(
            "https://cdn.example.com/content/abc0000000/a.mp3",
            contentUrl("https://cdn.example.com/content/", "a.mp3", asset),
        )
    }

    @Test
    fun emptyManifestMakesEveryAssetResolveAsBundled() {
        // The loader falls back to EMPTY when the JSON is unreadable; that must degrade to
        // pre-pack behaviour rather than to "everything is missing".
        assertTrue(ContentManifest.EMPTY.assets.isEmpty())
        assertTrue(ContentManifest.EMPTY.downloadablePackIds().isEmpty())
    }
}
