package me.matsumo.grabee.core.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val PlayfulMentorLight: ColorScheme = lightColorScheme(
    primary = Color(0xFFAB2C5D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E1),
    onPrimaryContainer = Color(0xFF8B0E45),
    inversePrimary = Color(0xFFFFB1C5),
    secondary = Color(0xFF006688),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFC2E8FF),
    onSecondaryContainer = Color(0xFF004D67),
    tertiary = Color(0xFF735C00),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFE087),
    onTertiaryContainer = Color(0xFF574500),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF26181B),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF26181B),
    surfaceVariant = Color(0xFFF6DCE1),
    onSurfaceVariant = Color(0xFF5B3F46),
    surfaceTint = Color(0xFFAB2C5D),
    inverseSurface = Color(0xFF3C2C30),
    inverseOnSurface = Color(0xFFFFECEF),
    outline = Color(0xFF8F6F76),
    outlineVariant = Color(0xFFE3BDC5),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F8),
    surfaceDim = Color(0xFFEDD4D8),
    surfaceContainer = Color(0xFFFFE8EC),
    surfaceContainerHigh = Color(0xFFFCE2E7),
    surfaceContainerHighest = Color(0xFFF6DCE1),
    surfaceContainerLow = Color(0xFFFFF0F2),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

val FluidArchitectLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF0058BC),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF0070EB),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFFADC6FF),
    secondary = Color(0xFF005B9E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFC0E8FF),
    onSecondaryContainer = Color(0xFF001E3C),
    tertiary = Color(0xFF00677E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF89F5E7),
    onTertiaryContainer = Color(0xFF002027),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF7F9FB),
    onBackground = Color(0xFF191C1E),
    surface = Color(0xFFF7F9FB),
    onSurface = Color(0xFF191C1E),
    surfaceVariant = Color(0xFFDCE3EB),
    onSurfaceVariant = Color(0xFF414755),
    surfaceTint = Color(0xFF0058BC),
    inverseSurface = Color(0xFF2E3135),
    inverseOnSurface = Color(0xFFEEF1F5),
    outline = Color(0xFF737885),
    outlineVariant = Color(0xFFC2C7D2),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFD8DBDF),
    surfaceContainer = Color(0xFFEAEDF1),
    surfaceContainerHigh = Color(0xFFE4E7EB),
    surfaceContainerHighest = Color(0xFFDEE1E5),
    surfaceContainerLow = Color(0xFFF0F3F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)
